server:
  port: 8027
spring:
  application:
    name: prueba-tecnica
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/db_test
    username: sisapp
    password: sisapp98
  jpa:
    open-in-view: true
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        max_fetch_depth: 5
        dialect: org.hibernate.dialect.PostgreSQLDialect